M48
; DRILL file {KiCad (6.0.4)} date Thu Apr 28 22:30:48 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-28T22:30:48-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.8319Y-2.0039
X2.8319Y-4.25
X6.8Y-2.95
X6.8303Y-2.0039
X6.8303Y-4.25
T0
M30
